import 'package:flutter/material.dart';
import 'package:wefix/Data/Functions/app_size.dart';
import 'package:wefix/Presentation/Loading/loading_text.dart';

class LoadingAbouUs extends StatefulWidget {
  const LoadingAbouUs({super.key});

  @override
  State<LoadingAbouUs> createState() => _LoadingStateAbouUs();
}

class _LoadingStateAbouUs extends State<LoadingAbouUs> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        LoadingText(width: AppSize(context).width * 0.9),
      ],
    );
  }
}
