// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW43W9PBRVOBIjVeS87V_u4UazlYsJrr0',
    appId: '1:167167966746:web:85c20a877dc8bf70265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    authDomain: 'wefix-1b290.firebaseapp.com',
    storageBucket: 'wefix-1b290.firebasestorage.app',
    measurementId: 'G-WNMB5576H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cymu6Jg3F6YemkAoOSudmYKJkV7L7XI',
    appId: '1:167167966746:android:120dda2ff892529c265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    storageBucket: 'wefix-1b290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtqj4MSmuBeGoU6yAVa-uX-J8Wx6_eXA',
    appId: '1:167167966746:ios:0636fbb636433604265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    storageBucket: 'wefix-1b290.firebasestorage.app',
    androidClientId: '167167966746-00phnkj2k1n7992biiq3p31lpnarrgn8.apps.googleusercontent.com',
    iosClientId: '167167966746-jn3etauvntmk5q390pj5ifsradn31225.apps.googleusercontent.com',
    iosBundleId: 'com.tenderjo.wefixapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtqj4MSmuBeGoU6yAVa-uX-J8Wx6_eXA',
    appId: '1:167167966746:ios:0636fbb636433604265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    storageBucket: 'wefix-1b290.firebasestorage.app',
    androidClientId: '167167966746-00phnkj2k1n7992biiq3p31lpnarrgn8.apps.googleusercontent.com',
    iosClientId: '167167966746-jn3etauvntmk5q390pj5ifsradn31225.apps.googleusercontent.com',
    iosBundleId: 'com.tenderjo.wefixapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW43W9PBRVOBIjVeS87V_u4UazlYsJrr0',
    appId: '1:167167966746:web:c21580407350b73a265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    authDomain: 'wefix-1b290.firebaseapp.com',
    storageBucket: 'wefix-1b290.firebasestorage.app',
    measurementId: 'G-TWF4BF3FN8',
  );

}